export enum Permission {
    AUTO_APPROVE_SCREENSHOT = "AUTO_APPROVE_SCREENSHOT",
    CAN_REPORT = "CAN_REPORT",
    CAN_SUBMIT = "CAN_SUBMIT",
    CAN_REVIEW = "CAN_REVIEW",
    CAN_SCREENSHOT = "CAN_SCREENSHOT",
    CAN_MESSAGE = "CAN_MESSAGE",
}