version: 2.1

executors:
  node:
    working_directory: /tmp/int_tests
    docker:
      - image: node:12.18.4-buster-slim
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    integration-tests:
        executor: node
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Get Configuration
                command: |
                    cp src/config/config.dev.json src/config/config.json
            - run:
                name: Install Docker Compose
                command: |
                    apt update
                    apt install -y curl sudo python3 make build-essential
                    curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                    chmod +x ~/docker-compose
                    sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run:
                name: Setup Development Environment
                background: true
                command: |
                    docker-compose up -d
                    docker-compose ps
                    docker-compose logs -t --tail="all" int_tests_df2-server_1
            - run:
                name: Wait For Server Warmup
                command: |
                    npm i -d
                    until curl -s 127.0.0.1:4201/api/ping/; do true; done > /dev/null
                    docker ps
            - run:
                name: Run Integration Tests
                command: |
                    npm run test-int
    docker:
        parameters:
            with_publish:
                type: boolean
                default: false
        executor: docker
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Build
                command: |
                    apk add --no-cache git
                    git fetch --tags
                    docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:latest -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:$(git describe) .
            - when:
                condition: <<parameters.with_publish>>
                steps:
                    - run:
                        name: Publish
                        command: |
                            echo $CONTAINER_REGISTRY_PASS | docker login ghcr.io -u $CONTAINER_REGISTRY_USER --password-stdin
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:latest
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:$(git describe)
                            
workflows:
    version: 2
    testing:
        jobs:
            - docker:
                name: Build & Publish
                with_publish: true
                filters:
                    branches:
                        only: master
            - integration-tests:
                name: Integration Tests
                requires:
                    - Build & Publish