version: 2.1

executors:
  node:
    working_directory: /tmp/int_tests
    docker:
      - image: node:12.18.4-buster-slim
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    integration-tests:
        executor: node
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Get Configuration
                command: |
                    cp src/config/config.dev.json src/config/config.json
            - run:
                name: Install Docker & Docker Compose
                command: |
                    apt update
                    apt install -y curl
                    echo "deb https://download.docker.com/linux/debian/ buster stable" >> /etc/apt/sources.list
                    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
                    apt update
                    apt install -y apt-transport-https ca-certificates gnupg lsb-release sudo git python3 make build-essential docker-ce=17.12.0~ce-0
                    curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                    chmod +x ~/docker-compose
                    sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run:
                name: Setup Testing Environment
                command: |
                    docker-compose up -d
                    docker-compose ps
                    docker-compose logs -t --tail="all" df2-server
                    docker ps
            - run:
                name: Wait For Server Warmup
                command: |
                    npm i -d
                    git clone https://github.com/vishnubob/wait-for-it
                    chmod +x ./wait-for-it/wait-for-it.sh
                    until ./wait-for-it/wait-for-it.sh localhost:4201 -t 3
                    do
                        docker-compose ps
                        docker-compose logs -t --tail="all" df2-server
                    done
                    docker ps
            - run:
                name: Run Integration Tests
                command: |
                    npm run test-int
    docker:
        parameters:
            with_publish:
                type: boolean
                default: false
        executor: docker
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Build
                command: |
                    apk add --no-cache git
                    git fetch --tags
                    docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:latest -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:$(git describe) .
            - when:
                condition: <<parameters.with_publish>>
                steps:
                    - run:
                        name: Publish
                        command: |
                            echo $CONTAINER_REGISTRY_PASS | docker login ghcr.io -u $CONTAINER_REGISTRY_USER --password-stdin
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:latest
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/reimagined-succotash:$(git describe)
                            
workflows:
    version: 2
    testing:
        jobs:
            - docker:
                name: Build & Publish
                with_publish: false
                filters:
                    branches:
                        only: master
            - integration-tests:
                name: Integration Tests
                requires:
                    - Build & Publish